name: CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/download-artifact@v1
      with:
        name: tests
    - name: Run Tests
      run: chmod 0755 tests/testapp && tests/testapp
