name: CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
    
      - name: Display structure of downloaded files
        run: ls -R

