#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: test

on:
  repository_dispatch:
  workflow_dispatch:
  
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3 

    
    - name: Download artifact package
      id: package
      run: |
        sudo mkdir -p /openwrt/bin/targets
        sudo wget -q -o https://github.com/localice2021/Phicomm_N1/suites/16979287444/artifacts/970214690 | tar -xzf -C openwrt/bin/targets
        ls -R
